### PR TITLE
Thin-wrapper refactor

### PR DESCRIPTION
**Pull request by mrecachinas**
Addresses #13, #36, and indirectly #11. This also includes adding a traitlet for `progress` when downloading a remote asset. Also, this changes the name from `sigplot.SigPlot` to `sigplot.Plot` to match the JS.

## TODO:
- [x] Back-end
    - [x] Refactor
    - [x] Test
        - [x] Test 1-D plotting
        - [x] Test 2-D plotting (with 2-D arrays as well as 1-D arrays both with subsize)
- [x] Front-end
    - [x] Refactor
    - [x] Test
        - [x] Test `change_settings`
        - [x] Test `overlay_array`
        - [x] Test `overlay_href`
            - [x] Test single local href
            - [x] Test single remote href
            - [x] Test two hrefs delimited by '|'
- [x] Optimize array passing by using binary serialization

Will do in subsequent PRs:
- Determine how to handle `plot.get_layer(lyr)` and other such methods
- Ensure progress updates work and print appropriately (tqdm-style?)
- Figure out how to handle passing callback functions

### CODE REVIEW

**Comment by mrecachinas** [comment]
2392e42 addresses #44.

```python
%%time

# self-explanatory, but we're instantiating a `SigPlot` object
# and saying do not show the x and y axes.
plot = Plot(noxaxis=True, noyaxis=True)

# Multiple `overlay_*` calls will layer on top of one-another
x = np.arange(0, 200e3, .01)
plot.overlay_array(np.sin(x))
```

yielded
```
CPU times: user 517 ms, sys: 199 ms, total: 717 ms
Wall time: 725 ms
```

**Comment by mrecachinas** [comment]
@sterre @maihde Let me know your thoughts. This implements a thinly veiled wrapper around sigplot.js where you call the same methods with roughly the same arguments as you do in JS.

As I said in the original comment, some details need to be fleshed out -- like how do you provide a callback? Do we instead pass a python callback or still a JS callback? Do we provide support for methods that return like `plot.get_layer(...)`?

Lastly, do we provide support for plotting multiple files in a single `overlay_href` when sigplot.js currently doesn't support that? This either requires sending the bar-delimited arguments to the client one-by-one or sending the client the args and letting the client handle it. I've implemented the former, but it doesn't appear to be working (for `plot.overlay_href('sin.tmp|pulse.tmp')`, it's only sending one command with `'sin.tmp'` to the client currently).

**Comment by sterre** [comment]
I'm not clear on how the new code here accepts everything that `_prepare_array_input` did before (tuples, lists, lists of lists, as well as, of course, ndarrays). Does that all still work as before?

I'm also not clear that this will handle the race conditions where you're evaluating all cells in a notebook (like with Run All Cells), and the server half of the widget assigns to traitlets before the client half of the widget has registered a listener (the reason for the `oldArrays` and `oldHrefs` before. Does this still work okay?

> As I said in the original comment, some details need to be fleshed out -- e.g., how do you provide a callback (to overlay_href)? Do we instead pass a python callback or still a JS callback? Do we provide support for methods that return like plot.get_layer(...)? Other methods that could be whitelisted: overlay_pipe and headermod.

For this particular PR, I'd say we don't need to worry about it yet, because those are both new features in the Jupyter context. However:
* I like the ability to put in Python callbacks. We could do this with a generic callback on the client side that just triggers the server (e.g., via traitlet assignment). The the server could keep a list of callbacks, kind of like the `onexit` list, and run through them. This would allow any combination of Python and JS callbacks, too.
* I think the ability to operate on a layer is important enough that we should implement that eventually. I imagine some sort of proxy object in Python, to make the syntax more natural.

> Lastly, do we provide support for plotting multiple files in a single overlay_href when sigplot.js currently doesn't support that? This either requires sending the bar-delimited arguments to the client one-by-one or sending the client the args and letting the client handle it (and break it up to one-by-one). I've implemented the former, but it doesn't appear to be working (for plot.overlay_href('sin.tmp|pulse.tmp') it's only sending one command with 'sin.tmp' to the client currently).

If we do allow the bar syntax on the client side, I think it should be all the way in SigPlot proper, not just in the Jupyter widget. (Perhaps that goes without saying when we're talking about "thin wrappers"!) But since it's more idiomatic in both Python and Javascript to give a real list of arguments, and since that syntax also allows us to specify both hrefs and arrays in one call, it seems better to me. (`plot(arr2, href1, href2, arr2)`

BTW one improvement from the thin wrapper approach is that it keeps the layer ordering the same as the call ordering. In the current code, all arrays are plotted in one pass, and all hrefs in another, so the layer order is jumbled.

**Comment by sterre** [comment]
What do you like about `sync_command_and_arguments({...})` vice direct assignment to `command_and_arguments = {...}`?

**Comment by mrecachinas** [comment]
@sterre Thanks for your thoughts --

> I'm not clear on how the new code here accepts everything that _prepare_array_input did before (tuples, lists, lists of lists, as well as, of course, ndarrays). Does that all still work as before?

It is more in-line with the sigplot.js argument. See the example notebook where I illustrate that the following two are equivalent.

```python
plot.overlay_array([1,2,3,2,3,4,1,2,3], {'subsize': 3})
plot.overlay_array([[1,2,3],[2,3,4],[1,2,3]], {'subsize': 3})
```

That shows Python lists. Numpy `ndarray`s are shown by the ambitious

```python
x = np.arange(0, 200e3, .01)
plot.overlay_array(np.sin(x))
```

Although I don't have an example of tuples, feel free to try it out in the first cell. Just tested the following and it worked.

```
plot.overlay_array((1,2,3))
```

> I'm also not clear that this will handle the race conditions where you're evaluating all cells in a notebook (like with Run All Cells), and the server half of the widget assigns to traitlets before the client half of the widget has registered a listener (the reason for the oldArrays and oldHrefs before. Does this still work okay?

Recall that each instance of `Plot` has its own websocket connected and client-side widget. The only race-condition-like behavior I'm seeing involves `plot.overlay_href('foo|bar')`, and I think something else is going on there.

> I imagine some sort of proxy object in Python, to make the syntax more natural.

Yep, @maihde and I discussed this briefly today and agreed this is the path forward for passing results from client to server.

> If we do allow the bar syntax on the client side, I think it should be all the way in SigPlot proper, not just in the Jupyter widget. (Perhaps that goes without saying when we're talking about "thin wrappers"!) 

Agreed. This should be fairly straightforward to implement in sigplot.js.

> BTW one improvement from the thin wrapper approach is that it keeps the layer ordering the same as the call ordering. In the current code, all arrays are plotted in one pass, and all hrefs in another, so the layer order is jumbled.

😄 _Explicit is better than implicit..._

> What do you like about `sync_command_and_arguments({...})` vice direct assignment to `command_and_arguments = {...}`?

1. It's marginally easier to mock in unit tests than `traitlets.Dict.__set__` or whatever they call on assignment, especially in situations where we (currently, under the hood) run that multiple times -- e.g., `overlay_href('foo|bar')` translates to two quick assignments.
2. I'm not married to using this traitlet in the long-term. I would prefer to plug-in directly to the `publish` or `send` COMM method that they're calling under the hood; this abstracts it so I can change the assignment to a method call.

Open to thoughts on this though.

> But since it's more idiomatic in both Python and Javascript to give a real list of arguments, and since that syntax also allows us to specify both hrefs and arrays in one call, it seems better to me. (plot(arr2, href1, href2, arr2)

I agree. We can do this in a `plot` method if you think that would work. Note though that this does diverge slightly from the sigplot.js API as well as the matplotlib/bokeh API (N.B. they do have a `plot_multiple` method, which would be exactly this). Also, this would require bookkeeping if a user wanted different callbacks per file (or callbacks in general).

**Comment by sterre** [comment]
I'm basically agreed on everything, with minor continued thoughts/questions below. 

> plot.overlay_array([[1,2,3],[2,3,4],[1,2,3]], {'subsize': 3})

I thought part of the goal was to be able to say just `plot.overlay_array([[1,2,3],[2,3,4],[1,2,3]])`, and infer the subsize from the shape of the array. But as I'm writing this, I realize that _in Javascript_ we don't have a native 2d array type like the numpy one, so of course you have to be explicit about subsize. So yeah, agreed on that one after all.

The issue with the race condition was one that I saw back before @amatma started work on this, based on the 2015 prototype, and it was exactly that case where I would create a plot and call an overlay function a time or two, all in one cell. So I thought, just from reading the code, that a big part of the `plot()` and `oldArrays` ideas had to do with fixing that race condition (which it did). The race, as far as I could trace it down, was that the server side widget would construct, the client side widget _model_ would construct, the server side widget would post an overlay or similar to the comm/traitlet, the client side widget _view_ would construct and add a listener to the comm. So the initial plot/overlay commands would be lost because the listener was added after the message was posted. 

There's been enough rearchitecture since that old prototype version that maybe all is well now. I'll keep an eye out for it anyway.

**Comment by mrecachinas** [comment]
> There's been enough rearchitecture since that old prototype version that maybe all is well now. I'll keep an eye out for it anyway.

Definitely let me know if this is the case.

In the meantime, I've submitted a PR to sigplot.js for `overlay_href('foo|bar')` support. Also, Michael Kellogg found a workaround to the weird behavior I was seeing with Python-server-side `plot.overlay_href('foo|bar')` that I'll push shortly.

**Comment by mrecachinas** [comment]
@sterre How do we feel about merging this?

**Comment by sterre** [comment]
I like it! Merge away.

**Pull request merged**
